language: dart
dist: xenial
# additional packages installed on the OS
addons:
  apt:
    packages:
      - lib32stdc++6
install: echo "installing flutter"
before_script:
  - git clone https://github.com/flutter/flutter.git
  - ./fultter/bin/flutter doctor
script:
  # - cd app
  - ../flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache
